changerequest/urls.py
"""django-changerequest URLs"""

from django.urls import path

from .views import HistoryDetailView, HistoryListView


app_name = 'history'
urlpatterns = [
    path('<int:pk>', HistoryDetailView.as_view(), name='detail'),
    path('<int:pk>/action', HistoryDetailView.as_view(), name='action'),  # TODO: Replace with proper view
    path('browse', HistoryListView.as_view(), name='browse'),
]

changerequest/models.py
"""django-changerequest models"""

import logging
import threading

from django.conf import settings
from django.core.cache import cache
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models
from django.urls import reverse
from django.utils.encoding import force_str
from django.utils.hashable import make_hashable

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages as msg

from .utils import (format_object_str, model_to_dict, data_m2m, formset_data_revert, formset_data_changed,
                    changed_keys, filter_data, get_ip_from_request, objectdict)

logger = logging.getLogger(__name__)


class ChangeRequest(models.Model):
    thread = threading.local()  # Used to store request via middleware

    class Type(models.IntegerChoices):
        """Constants that define actions for which ChangeRequest records can be saved

        The first three are obvious; 'Related' is used for associated data that usually
        has a 1-N relation with the main model for which history is being saved.
        """
        ADD = 1
        MODIFY = 2
        DELETE = 3
        RELATED = 4

    class Status(models.IntegerChoices):
        """Constants that define the status of a ChangeRequest

        Pending    = ChangeRequest is awaiting moderation; data is not yet committed to the database
        Approved   = ChangeRequest has been (automatically) approved and data is committed to the database
        Denied     = A moderator has denied the ChangeRequest
        Withdrawn  = The user has withdrawn the ChangeRequest themselves
        Reverted   = A moderator has "undone" the approval of a ChangeRequest and reverted data to how it was before
        """
        PENDING = 1
        APPROVED = 2
        DENIED = 3
        WITHDRAWN = 4
        REVERTED = 5

    # ChangeRequest does not support non-integer primary keys
    object_type = models.ForeignKey(ContentType, related_name='%(class)s_object', on_delete=models.PROTECT)
    object_id = models.PositiveIntegerField(null=True, blank=True)
    object = GenericForeignKey('object_type', 'object_id')
    object_str = models.CharField(max_length=250, blank=True)
    related_type = models.ForeignKey(ContentType, null=True, blank=True, related_name='%(class)s_related',
                                     on_delete=models.PROTECT)
    request_type = models.PositiveSmallIntegerField(choices=Type.choices)
    status = models.PositiveSmallIntegerField(choices=Status.choices, default=Status.PENDING)
    data_revert = models.JSONField(encoder=DjangoJSONEncoder, null=True, blank=True)
    data_changed = models.JSONField(encoder=DjangoJSONEncoder, null=True, blank=True)
    comment = models.TextField(blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='%(class)s_user', on_delete=models.PROTECT)
    user_ip = models.GenericIPAddressField(unpack_ipv4=True)
    mod = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='%(class)s_mod', null=True, blank=True,
                            on_delete=models.PROTECT)
    mod_ip = models.GenericIPAddressField(unpack_ipv4=True, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, blank=True)
    date_modified = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return format_object_str(self.get_object_type(), self.object_str, self.object_id)
    
    @classmethod
    def get_request(cls):
        return cls.thread.request

    @classmethod
    def create(cls, obj: 'HistoryModel', request_type: int = None) -> object:
        """Creates a ChangeRequest object"""
        cr = cls()
        cr.set_object(obj)
        cr.set_request_type(request_type)
        cr.status = ChangeRequest.Status.PENDING
        if cr.request_type != ChangeRequest.Type.RELATED:
            cr.data_revert = obj.data_revert()
            cr.data_changed = model_to_dict(obj)
            if cr.request_type == ChangeRequest.Type.DELETE:
                cr.data_changed = None  # Changes do not matter in case of deletion
        cr.set_user(ChangeRequest.get_request())
        return cr

    def set_object(self, obj: models.Model):
        if obj.pk:
            # Existing object
            self.object = obj
        else:
            # New object
            self.object_type = ContentType.objects.get_for_model(obj)
            self.object_id = None
        self.object_str = str(obj)

    def cache_object_type(self, object_type_id=None, object_type=None):
        # cache.get_or_set() is not usable here because accessing self.object_type members trigger database queries
        obj_type_id = object_type_id if object_type_id is not None else self.object_type_id
        model = cache.get(f'object-type-{obj_type_id}')
        if model is None:
            model = object_type.model_class() if object_type is not None else self.object_type.model_class()
            cache.set(f'object-type-{obj_type_id}', model)
        return model

    def get_object_type(self) -> str:
        # Django 3.0 now adds app label to string representation of object_type, so get model name another way
        return self.cache_object_type()._meta.verbose_name

    def get_related_type(self) -> str:
        return self.cache_object_type(self.related_type_id, self.related_type)._meta.verbose_name

    def set_request_type(self, request_type: int = None):
        if request_type is not None:
            self.request_type = request_type
        elif self.related_type is not None:
            self.request_type = ChangeRequest.Type.RELATED
        elif self.object is not None:
            self.request_type = ChangeRequest.Type.MODIFY
        else:
            self.request_type = ChangeRequest.Type.ADD

    def set_user(self, request: object):
        self.user = request.user
        self.user_ip = get_ip_from_request(request)

    def set_mod(self, request: object):
        self.mod = request.user
        self.mod_ip = get_ip_from_request(request)

    def log(self, action: str = None, obj: str = None):
        action = self.get_request_type_display() if action is None else action
        obj = self if obj is None else obj
        logger.info(f'ChangeRequest: [{action}] [{self.get_status_display()}] {obj}'
                    f' user "{self.user.username}" ({self.user.pk})' +
                    (f' mod "{self.mod.username}" ({self.mod.pk})' if self.mod else ''))

    def save(self, *args, **kwargs):
        # 1) Save ChangeRequest if request type is something like ADD or DELETE
        # -OR-
        # 2) Prevent duplicates: when modifying existing entries, only save if data_revert does not equal data_changed
        if (self.request_type not in (self.Type.MODIFY, self.Type.RELATED)) or (self.data_revert != self.data_changed):
            super().save(*args, **kwargs)

    def fields_verbose(self):
        return {f.name: f.verbose_name
                for f in self.cache_object_type()._meta.get_fields() if hasattr(f, 'verbose_name')}

    def resolve_field(self, name, value):
        field = self.cache_object_type()._meta.get_field(name)
        # Field is Foreign Key
        if isinstance(field, models.ForeignKey):
            try:
                obj = field.related_model.objects.get(**{field.remote_field.field_name: value})
                return str(obj)
            except models.ObjectDoesNotExist:
                pass  # Reference no longer exists (deleted?)
        if isinstance(field, models.ManyToManyField):
            try:
                qs = [models.Q(**{field.related_model._meta.pk.name: v}) for v in value]
                query = qs.pop()
                for q in qs:
                    query |= q
                return ', '.join(str(obj) for obj in field.related_model.objects.filter(query))
            except models.ObjectDoesNotExist:
                pass  # Reference no longer exists (deleted?)
        # Other fields (code copied straight from django/db/models/base.py :: _get_FIELD_display)
        choices_dict = dict(make_hashable(field.flatchoices))
        return force_str(choices_dict.get(make_hashable(value), value), strings_only=True)

    def order_fields(self, data, related=False) -> dict:
        # JSON dict order isn't guaranteed
        if related:
            model = self.cache_object_type(self.related_type_id, self.related_type)
        else:
            model = self.cache_object_type()
        return {f.name: data[f.name] for f in model._meta.get_fields() if f.name in data}

    def diff(self):
        # ADD
        if self.data_revert is None:
            return self.order_fields(self.data_changed)
        # DELETE
        if self.data_changed is None:
            return self.order_fields(self.data_revert)
        # MODIFY
        result = {k: v for k, v in self.data_changed.items() if k not in self.data_revert or self.data_revert[k] != v}
        return self.order_fields(result)
    
    def diff_related(self):
        result = {}
        # Primary Key Field Name
        result['pk'] = pk = self.cache_object_type(self.related_type_id, self.related_type)._meta.pk.name
        # Fields
        result['fields'] = [field for field in
                            self.cache_object_type(self.related_type_id, self.related_type)._meta.get_fields()
                            if isinstance(field, models.Field)]
        # Get list of primary key values from existing rows (data_revert) to be able to check for new data
        existing = [
            item[pk] for item in self.data_revert if pk in item and item[pk]
        ] if self.data_revert is not None else []
        # {action} values are for detail views; {action_str} values are for list views
        # Build list of added rows and changed rows from data_changed
        result['added'] = []
        result['added_str'] = []
        changed = {}
        if self.data_changed is not None:

changerequest/templates/history/_detail.html
{% extends 'base.html' %}
{% load history %}

{% block content %}
    <h1>{{ changerequest.get_object_type|title }} <span class="text-muted">History</span></h1>
    <div class="container">
{% with r='row py-1' h='col-lg-2 col-sm-3 pl-sm-2 font-weight-bold' d='col-lg-10 col-sm-9' %}
    <div class="{{ r }}">
        <div class="{{ h }}">Object</div>
        <div class="{{ d }}">
            {% if changerequest.object.get_absolute_url %}
                <a href="{{ changerequest.object.get_absolute_url }}">{{ changerequest.object }}</a>
            {% else %}
                {{ changerequest.object_str }}
            {% endif %}
            <small>({{ changerequest.get_object_type|title }} #{{ changerequest.object_id }})</small>
        </div>
    </div>
    <div class="{{ r }}">
        <div class="{{ h }}">Action</div>
        <div class="{{ d }}">
            <span class="badge {% if changerequest.request_type == changerequest.Type.ADD %}bg-success{% elif changerequest.request_type == changerequest.Type.MODIFY %}bg-info{% elif changerequest.request_type == changerequest.Type.DELETE %}bg-danger{% else %}badge-secondary{% endif %}">{{ changerequest.get_request_type_display }}</span>
            {% if changerequest.request_type == changerequest.Type.RELATED %} <strong>{{ changerequest.get_related_type|title }}</strong>{% endif %}</div>
    </div>
    <div class="{{ r }}">
        <div class="{{ h }}">Status</div>
        <div class="{{ d }}">
            <span class="badge {% if changerequest.status == changerequest.Status.PENDING %}bg-info{% elif changerequest.status == changerequest.Status.APPROVED %}bg-success{% elif changerequest.status == changerequest.Status.DENIED %}bg-warning{% elif changerequest.status == changerequest.Status.REVERTED %}bg-danger{% else %}badge-secondary{% endif %}">{{ changerequest.get_status_display }}</span>
        </div>
    </div>
    <div class="{{ r }}">
        <div class="{{ h }}">Changes</div>
        <div class="{{ d }}">
            <div class="table-responsive">
            <table class="table table-sm">
                {% if changerequest.request_type == changerequest.Type.RELATED %}
                    {% with diff=changerequest.diff_related %}
                    <thead>
                        <tr>
                        {% for field in diff.fields %}
                            <th>{{ field.name|title }}</th>
                        {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                    {% for key, item in diff.existing.items %}
                        {% with pk=item|_history_get:diff.pk %}
                        <tr{% if pk in diff.deleted %} class="table-danger alert-danger"{% endif %}>
                        {% for key, value in item.items %}
                            {% if key == diff.pk %}<th>{% else %}<td>{% endif %}
                        {% if key in diff.modified|_history_get:pk and pk not in diff.deleted %}<span class="alert-success px-1">{{ value }}</span>{% else %}{{ value }}{% endif %}
                            {% if key == diff.pk %}</th>{% else %}</td>{% endif %}
                        {% endfor %}
                        </tr>
                        {% endwith %}
                    {% endfor %}
                    {% for item in diff.added %}
                        <tr class="table-success alert-success">
                        {% for key, value in item.items %}
                            {% if key == diff.pk %}<th>{% else %}<td>{% endif %}
                            {{ value }}
                            {% if key == diff.pk %}</th>{% else %}</td>{% endif %}
                        {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                    {% endwith %}
                {% else %}
                    <thead>
                        <tr>
                            <th>Field</th>
                            <th>Old</th>
                            <th>New</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% with verbose=changerequest.fields_verbose %}
                    {% for key, value in changerequest.diff.items %}
                        <tr>
                            <th>{{ verbose|_history_get:key|title }}</th>
                            {% if changerequest.request_type == changerequest.Type.ADD %}
                                <td><span class="text-danger">-</span></td>
                                <td>{% if value %}<span class="alert-success px-1">{% _history_resolve changerequest key value %}</span>{% else %}<span class="text-success">-</span>{% endif %}</td>
                            {% elif changerequest.request_type == changerequest.Type.MODIFY %}
                                <td>
                                    {% if changerequest.data_revert|_history_get:key %}
                                        <span class="alert-danger px-1">{% _history_resolve changerequest key changerequest.data_revert|_history_get:key %}</span>
                                    {% else %}
                                        <span class="text-danger">-</span>
                                    {% endif %}
                                </td>
                                <td>{% if value %}<span class="alert-success px-1">{% _history_resolve changerequest key value %}</span>{% else %}<span class="text-success">-</span>{% endif %}</td>
                            {% elif changerequest.request_type == changerequest.Type.DELETE %}
                                <td>{% if value %}<span class="alert-danger px-1">{% _history_resolve changerequest key value %}</span>{% else %}<span class="text-danger">-</span>{% endif %}</td>
                                <td><span class="text-success">-</span></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    {% endwith %}
                    </tbody>
                {% endif %}
            </table>
            </div>
        </div>
    </div>
    <div class="{{ r }}">
        <div class="{{ h }}">Comment</div>
        <div class="{{ d }}">{{ changerequest.comment|default:'-' }}</div>
    </div>
    <div class="{{ r }}">
        <div class="{{ h }}">User</div>
        <div class="{{ d }}">{% block user %}{{ changerequest.user.username }}{% endblock user %} <small>({{ changerequest.date_created }})</small></div>
    </div>
    {% if changerequest.mod is not None %}
    <div class="{{ r }}">
        <div class="{{ h }}">Mod</div>
        <div class="{{ d }}">{% block mod %}{{ changerequest.mod.username }}{% endblock mod %} <small>({{ changerequest.date_modified }})</small></div>
    </div>
    {% endif %}
    <form action="{% url 'history:action' changerequest.pk %}" method="post">
        {% csrf_token %}
	    <div class="row mt-3">
		    <div class="{{ h }}"></div>
		    <div class="{{ d }}">
                {% if changerequest.status == changerequest.Status.PENDING and perms.history.mod_approve %}
                    <button type="submit" name="action" value="approve" class="btn btn-primary my-2"><i class="far fa-thumbs-up"></i> Approve</button>
                    <button type="submit" name="action" value="deny" class="btn btn-primary my-2 ml-2"><i class="fas fa-ban"></i> Deny</button>
                {% endif %}
                {% if changerequest.status == changerequest.Status.APPROVED and perms.history.mod_approve %}
                    <button type="submit" name="action" value="revert" class="btn btn-primary my-2"><i class="fas fa-backspace"></i> Revert</button>
                {% endif %}
                {% if changerequest.status == changerequest.Status.PENDING and request.user == changerequest.user %}
                    <button type="submit" name="action" value="withdraw" class="btn btn-primary my-2"><i class="far fa-trash-alt"></i> Withdraw</button>
                {% endif %}
            </div>
        </div>
    </form>
{% endwith %}
    </div>
{% endblock content %}

changerequest/templates/history/_list.html
{% extends 'base.html' %}
{% load history %}

{% block content %}
    <div class="d-flex flex-wrap">
        <h1><span class="text-muted">Browse</span> History</h1>
        <div class="btn-group align-self-center ml-auto">
            <a href="{{ view.get_absolute_url }}{% _history_view_method view 'get_querystring' status='all' %}" class="btn btn{% if status == 'all' %}-primary{% else %}-outline-secondary{% endif %} btn-sm">All</a>
            <a href="{{ view.get_absolute_url }}{% _history_view_method view 'get_querystring' status='pending' %}" class="btn btn{% if status == 'pending' %}-info{% else %}-outline-secondary{% endif %} btn-sm">Pending</a>
            <a href="{{ view.get_absolute_url }}{% _history_view_method view 'get_querystring' status='approved' %}" class="btn btn{% if status == 'approved' %}-success{% else %}-outline-secondary{% endif %} btn-sm">Approved</a>
            <a href="{{ view.get_absolute_url }}{% _history_view_method view 'get_querystring' status='denied' %}" class="btn btn{% if status == 'denied' %}-warning{% else %}-outline-secondary{% endif %} btn-sm">Denied</a>
            <a href="{{ view.get_absolute_url }}{% _history_view_method view 'get_querystring' status='withdrawn' %}" class="btn btn{% if status == 'withdrawn' %}-secondary{% else %}-outline-secondary{% endif %} btn-sm">Withdrawn</a>
            <a href="{{ view.get_absolute_url }}{% _history_view_method view 'get_querystring' status='reverted' %}" class="btn btn{% if status == 'reverted' %}-danger{% else %}-outline-secondary{% endif %} btn-sm">Reverted</a>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-sm table-hover">
            <thead>
                <tr>
                    <th class="text-nowrap text-center">
                        <a href="{{ view.get_absolute_url }}{% _history_view_method view 'get_querystring' order='date' %}" class="text-body">Date</a>
                        <a href="{{ view.get_absolute_url }}{% _history_view_method view 'get_querystring' order='date' %}" class="text-body"><i class="fas fa-caret-{% _history_view_method view 'get_order_direction' order='date' %}"></i></a>
                    </th>
                    <th class="text-center" title="Action">A</th>
                    <th class="text-center" title="Status">S</th>
                    <th>Type</th>
                    <th>Object</th>
                    <th>Changes</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for cr in object_list %}
                <tr>
                    <td class="text-nowrap text-center"><small>{% if cr.date_modified %}{{ cr.date_modified|date:'SHORT_DATE_FORMAT' }}{% else %}{{ cr.date_created|date:'SHORT_DATE_FORMAT' }}{% endif %}</small></td>
                    <td class="text-center"><span class="badge {% if cr.request_type == cr.Type.ADD %}bg-success{% elif cr.request_type == cr.Type.MODIFY %}bg-info{% elif cr.request_type == cr.Type.DELETE %}bg-danger{% else %}bg-secondary{% endif %}" title="{{ cr.get_request_type_display }}">{{ cr.get_request_type_display|first }}</span></td>
                    <td class="text-center"><span class="badge {% if cr.status == cr.Status.PENDING %}bg-info{% elif cr.status == cr.Status.APPROVED %}bg-success{% elif cr.status == cr.Status.DENIED %}bg-warning{% elif cr.status == cr.Status.REVERTED %}bg-danger{% else %}bg-secondary{% endif %}" title="{{ cr.get_status_display }}">{{ cr.get_status_display|first }}</span></td>
                    <td class="text-nowrap"><small>{{ cr.get_object_type|title }}</small></td>
                    <td class="text-nowrap">
                        {% if cr.object.get_absolute_url %}
                            <a href="{{ cr.object.get_absolute_url }}">{{ cr.object }}</a>
                        {% else %}
                            {{ cr.object_str }}
                        {% endif %}
                    </td>
                    <td class="w-100">
                    {% if cr.request_type == cr.Type.RELATED %}
                        {% with diff=cr.diff_related %}
                            {% if diff.added_str|length > 0 %}
                                <small class="text-success">Add:</small>
                                {% for item in diff.added_str %}
                                    {{ item }}{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            {% endif %}
                            {% if diff.modified_str|length > 0 %}
                                <small class="text-info">Modify:</small>
                                {% for item in diff.modified_str %}
                                    {{ item }}{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            {% endif %}
                            {% if diff.deleted_str|length > 0 %}
                                <small class="text-danger">Delete:</small>
                                {% for item in diff.deleted_str %}
                                    {{ item }}{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            {% endif %}
                        {% endwith %}
                    {% elif cr.request_type != cr.Type.ADD %}
                        {% for field in cr.diff %}
                            {{ field|_history_underspace|title }}{% if not forloop.last %}, {% endif %}
                        {% empty %}
                            -
                        {% endfor %}
                    {% else %}
                        -
                    {% endif %}
                    </td>
                    <td class="text-nowrap">{% block user %}{{ cr.user.username }}{% endblock user %}</td>
                    <td>{% if perms.changerequest.view_changerequest %}<a class="btn btn-outline-secondary btn-sm py-0" href="{{ cr.get_absolute_url }}">View</a>{% endif %}</td>
                </tr>
            {% empty %}
                <tr><td class="font-italic text-center" colspan="8">None</td></tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
  {% if is_paginated %}
    {% block paginator %}
    {% endblock paginator %}
  {% endif %}
{% endblock content %}

changerequest/templates/history/_object.html
<h2>History</h2>
<div class="table-responsive">
    <table class="table table-sm table-hover">
        <thead>
            <tr>
                <th class="text-center">Date</th>
                <th class="text-center">Action</th>
                <th class="text-center">Status</th>
                <th>Changes</th>
                <th>User</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for cr in history %}
            <tr>
                <td class="text-nowrap text-center"><small>{% if cr.date_modified %}{{ cr.date_modified|date:'SHORT_DATETIME_FORMAT' }}{% else %}{{ cr.date_created|date:'SHORT_DATETIME_FORMAT' }}{% endif %}</small></td>
                <td class="text-center"><span class="badge {% if cr.request_type == cr.Type.ADD %}badge-success{% elif cr.request_type == cr.Type.MODIFY %}badge-info{% elif cr.request_type == cr.Type.DELETE %}badge-danger{% else %}badge-secondary{% endif %}">{{ cr.get_request_type_display }}</span></td>
                <td class="text-center"><span class="badge {% if cr.status == cr.Status.PENDING %}badge-info{% elif cr.status == cr.Status.APPROVED %}badge-success{% elif cr.status == cr.Status.DENIED %}badge-warning{% elif cr.status == cr.Status.REVERTED %}badge-danger{% else %}badge-secondary{% endif %}">{{ cr.get_status_display }}</span></td>
                <td class="w-100">
                {% if cr.request_type != cr.Type.ADD %}
                    {% for field in cr.diff %}
                        {{ field|title }}{% if not forloop.last %}, {% endif %}
                    {% empty %}
                        -
                    {% endfor %}
                {% else %}
                    -
                {% endif %}
                </td>
                <td class="text-nowrap">{% block user %}{{ cr.user.username }}{% endblock user %}</td>
                <td>{% if perms.changerequest.view_changerequest %}<a class="btn btn-outline-secondary btn-sm py-0" href="{{ cr.get_absolute_url }}">View</a>{% endif %}</td>
            </tr>
        {% empty %}
            <tr><td class="font-italic text-center" colspan="6">None</td></tr>
        {% endfor %}
        </tbody>
    </table>
</div>

changerequest/templates/history/_tag.html
{% load history %}
<h2>History</h2>
<div class="table-responsive">
    <table class="table table-sm table-hover">
        <thead>
            <tr>
                <th class="text-center">Date</th>
                <th class="text-center">Action</th>
                <th class="text-center">Status</th>
                <th>Changes</th>
                <th>User</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for cr in history %}
            <tr>
                <td class="text-nowrap text-center"><small>{% if cr.date_modified %}{{ cr.date_modified|date:'SHORT_DATETIME_FORMAT' }}{% else %}{{ cr.date_created|date:'SHORT_DATETIME_FORMAT' }}{% endif %}</small></td>
                <td class="text-center"><span class="badge {% if cr.request_type == cr.Type.ADD %}bg-success{% elif cr.request_type == cr.Type.MODIFY %}bg-info{% elif cr.request_type == cr.Type.DELETE %}bg-danger{% else %}bg-secondary{% endif %}">{{ cr.get_request_type_display }}</span></td>
                <td class="text-center"><span class="badge {% if cr.status == cr.Status.PENDING %}bg-info{% elif cr.status == cr.Status.APPROVED %}bg-success{% elif cr.status == cr.Status.DENIED %}bg-warning{% elif cr.status == cr.Status.REVERTED %}bg-danger{% else %}bg-secondary{% endif %}">{{ cr.get_status_display }}</span></td>
                <td class="w-100">
                {% if cr.request_type == cr.Type.RELATED %}
                    {% with diff=cr.diff_related %}
                        {% if diff.added_str|length > 0 %}
                            <small class="text-success">Add:</small>
                            {% for item in diff.added_str %}
                                {{ item }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        {% endif %}
                        {% if diff.modified_str|length > 0 %}
                            <small class="text-info">Modify:</small>
                            {% for item in diff.modified_str %}
                                {{ item }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        {% endif %}
                        {% if diff.deleted_str|length > 0 %}
                            <small class="text-danger">Delete:</small>
                            {% for item in diff.deleted_str %}
                                {{ item }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                {% elif cr.request_type != cr.Type.ADD %}
                    {% for field in cr.diff %}
                        {{ field|_history_underspace|title }}{% if not forloop.last %}, {% endif %}
                    {% empty %}
                        -
                    {% endfor %}
                {% else %}
                    -
                {% endif %}
                </td>
                <td class="text-nowrap">{% block user %}{{ cr.user.username }}{% endblock user %}</td>
                <td>{% if perms.changerequest.view_changerequest %}<a class="btn btn-outline-secondary btn-sm py-0" href="{{ cr.get_absolute_url }}">View</a>{% endif %}</td>
            </tr>
        {% empty %}
            <tr><td class="font-italic text-center" colspan="6">None</td></tr>
        {% endfor %}
        </tbody>
    </table>
</div>

changerequest/templates/history/detail.html
{% extends 'history/_detail.html' %}

changerequest/templates/history/list.html
{% extends 'history/_list.html' %}

changerequest/templates/history/tag.html
{% extends 'history/_tag.html' %}